/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserPage;

/**
 *
 * @author AqilR
 */
public class NewHome extends javax.swing.JFrame {

    /**
     * Creates new form NewHome
     */
    public NewHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Kamar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Fasilitas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Login = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Register = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        homeImage = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(getPreferredSize());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navbar.setBackground(new java.awt.Color(51, 204, 0));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setBackground(new java.awt.Color(51, 204, 0));
        Home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("HOME");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        navbar.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 140, 60));

        Kamar.setBackground(new java.awt.Color(51, 204, 0));
        Kamar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Kamar.setPreferredSize(new java.awt.Dimension(140, 100));

        jLabel2.setText("KAMAR");

        javax.swing.GroupLayout KamarLayout = new javax.swing.GroupLayout(Kamar);
        Kamar.setLayout(KamarLayout);
        KamarLayout.setHorizontalGroup(
            KamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KamarLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        KamarLayout.setVerticalGroup(
            KamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KamarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        navbar.add(Kamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, 60));

        Fasilitas.setBackground(new java.awt.Color(51, 204, 0));
        Fasilitas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Fasilitas.setPreferredSize(new java.awt.Dimension(140, 100));

        jLabel3.setText("FASILITAS");

        javax.swing.GroupLayout FasilitasLayout = new javax.swing.GroupLayout(Fasilitas);
        Fasilitas.setLayout(FasilitasLayout);
        FasilitasLayout.setHorizontalGroup(
            FasilitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FasilitasLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        FasilitasLayout.setVerticalGroup(
            FasilitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FasilitasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        navbar.add(Fasilitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, 60));

        Login.setBackground(new java.awt.Color(51, 204, 0));
        Login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Login.setPreferredSize(new java.awt.Dimension(140, 100));

        jLabel5.setText("LOGIN");

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(21, 21, 21))
        );

        navbar.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, -1, 60));

        Register.setBackground(new java.awt.Color(51, 204, 0));
        Register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Register.setPreferredSize(new java.awt.Dimension(140, 100));

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("REGISTER");

        javax.swing.GroupLayout RegisterLayout = new javax.swing.GroupLayout(Register);
        Register.setLayout(RegisterLayout);
        RegisterLayout.setHorizontalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        RegisterLayout.setVerticalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        navbar.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 130, 60));

        jLabel6.setText("ZENITH HOTEL");
        navbar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 110, -1));

        getContentPane().add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 908, 60));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setName(""); // NOI18N
        content.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                contentPropertyChange(evt);
            }
        });
        content.setLayout(new java.awt.BorderLayout());

        homeImage.setBackground(new java.awt.Color(255, 255, 255));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserPage/fernando-alvarez-rodriguez-M7GddPqJowg-unsplash 1.png"))); // NOI18N
        image.setText("image");

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(10);
        jTextArea1.setText("\t\tSelamat datang di Zenith Hotel, platform terdepan untuk merencanakan perjalanan Anda dengan mudah. \n\nKami menawarkan akses luas ke jaringan hotel di seluruh dunia, menyediakan pilihan akomodasi mulai dari yang mewah hingga yang terjangkau. Dengan harga terbaik, kami berkomitmen memberikan nilai terbaik bagi pelanggan kami. Temukan informasi wisata terkini dan rekomendasi lokal, serta nikmati layanan pelanggan 24/7 yang siap membantu setiap kebutuhan perjalanan Anda. Keamanan dan privasi data Anda adalah prioritas kami, dan kami menggunakan teknologi enkripsi terkini.  \n\t\tTerima kasih telah memilih Zenith Hotel sebagai mitra perjalanan Anda. Selamat menikmati perjalanan!");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setFocusable(false);
        jTextArea1.setMargin(new java.awt.Insets(10, 20, 2, 20));
        jScrollPane1.setViewportView(jTextArea1);

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setText("ZENITH HOTEL");

        javax.swing.GroupLayout homeImageLayout = new javax.swing.GroupLayout(homeImage);
        homeImage.setLayout(homeImageLayout);
        homeImageLayout.setHorizontalGroup(
            homeImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeImageLayout.createSequentialGroup()
                .addGroup(homeImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(homeImageLayout.createSequentialGroup()
                        .addGroup(homeImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homeImageLayout.createSequentialGroup()
                                .addGap(369, 369, 369)
                                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        homeImageLayout.setVerticalGroup(
            homeImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeImageLayout.createSequentialGroup()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        content.add(homeImage, java.awt.BorderLayout.CENTER);

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 920, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contentPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_contentPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_contentPropertyChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fasilitas;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Kamar;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Register;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel content;
    private javax.swing.JPanel homeImage;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel navbar;
    // End of variables declaration//GEN-END:variables
}
